import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_FILE = path.join(__dirname, 'store.json');

const defaultData = {
  shopInfo: {
    name: "Nakshatra Designer's",
    tagline: "Bridal Blouse, Designer Frocks, Saree Conversion & Aari Studio",
    established: "Est. 2000 (25+ Years of Excellence)",
    address: "No 62/2, Everest Balaji Arcade, South Car Street (Opp. Sivakumar Metal Mart), Tiruchengode West, Tiruchengode - 637211",
    phones: ["+91 91235 14214", "+91 91235 00065"],
    whatsapp: "+919123514214",
    rating: "4.9 ⭐ (Justdial - 28+ Verified Reviews) | 5.0 ⭐ (Google)",
    hours: "Mon – Sat: 9:30 AM – 8:00 PM | Sun: 11:00 AM – 2:00 PM",
    instagram: "@nakshatra_designers_2101"
  },
  options: {
    garmentTypes: [
      { id: 'saree_blouse', name: 'Custom Saree Blouse', basePrice: 650, desc: 'Bridal Aari work, puff sleeves & designer saree blouses' },
      { id: 'designer_frock', name: 'Designer Frock / Long Dress', basePrice: 950, desc: 'Custom frocks, Anarkali gowns & kids/women dresses' },
      { id: 'saree_to_frock', name: 'Saree Converted Frock (Saree Reuse)', basePrice: 1200, desc: 'Repurpose old or silk sarees into grand designer frocks & maxi gowns' },
      { id: 'saree_pleating', name: 'Saree Pre-Pleating & Box Folding', basePrice: 350, desc: 'Professional saree pre-pleating for 1-minute wearing' },
      { id: 'skirt_shirt', name: 'Skirt Shirt & Ethnic Kids Wear', basePrice: 850, desc: 'Custom designer skirt and top / shirt tailoring for kids & women' },
      { id: 'salwar_kurti', name: 'Designer Salwar & Kurti Set', basePrice: 550, desc: 'Custom kurti, pant & dupatta tailoring' },
      { id: 'lehenga_set', name: 'Bridal / Festive Lehenga Choli', basePrice: 1400, desc: 'Heavy flare lehenga skirt & blouse tailoring' }
    ],
    frockFlares: [
      { id: 'umbrella_flare', name: 'Umbrella Circle Flare (360° Gown)', price: 300, desc: '360 degree grand circular flare' },
      { id: 'pleated_box', name: 'Box Pleated Royal Flare', price: 250, desc: 'Classic structured box pleats' },
      { id: 'tiered_layers', name: 'Multi-Layered Tiered Frock', price: 400, desc: 'Layered ruffle & gather style' },
      { id: 'straight_maxi', name: 'Straight Cut Elegant Maxi Frock', price: 150, desc: 'Sleek A-line silhouette' }
    ],
    frontNecks: [
      { id: 'sweetheart', name: 'Sweetheart Neck', price: 0, previewType: 'sweetheart' },
      { id: 'boat', name: 'Boat Neck', price: 100, previewType: 'boat' },
      { id: 'deep_u', name: 'Deep U Neck', price: 0, previewType: 'deep_u' },
      { id: 'high_collar', name: 'High Collar / Mandarin', price: 250, previewType: 'high_collar' },
      { id: 'potli_front', name: 'Front Placket with Potli Buttons', price: 200, previewType: 'potli_front' },
      { id: 'deep_v', name: 'Royal V Neck', price: 150, previewType: 'deep_v' }
    ],
    backNecks: [
      { id: 'deep_u_back', name: 'Deep U with Dori & Tassels', price: 150, previewType: 'deep_u_back' },
      { id: 'open_back', name: 'Square Open Back', price: 100, previewType: 'open_back' },
      { id: 'window_cutout', name: 'Diamond Cutout Window', price: 200, previewType: 'window_cutout' },
      { id: 'bow_back', name: 'Statement Ribbon Bow Back', price: 250, previewType: 'bow_back' },
      { id: 'potli_keyhole', name: 'Oval Keyhole with Potli Accent', price: 180, previewType: 'potli_keyhole' }
    ],
    sleeves: [
      { id: 'short', name: 'Classic Short Sleeve (5-6")', price: 0, length: 'short' },
      { id: 'elbow', name: 'Elbow Length (10-11")', price: 150, length: 'elbow' },
      { id: 'three_fourth', name: '3/4th Sleeve (14-15")', price: 200, length: 'three_fourth' },
      { id: 'full', name: 'Full Length Sleeve (20")', price: 250, length: 'full' },
      { id: 'puff', name: 'Traditional South Indian Puff Sleeve', price: 300, length: 'puff' },
      { id: 'sleeveless', name: 'Sleeveless', price: 0, length: 'sleeveless' },
      { id: 'cold_shoulder', name: 'Cold Shoulder Cut', price: 220, length: 'cold_shoulder' }
    ],
    fabrics: [
      { id: 'kanjivaram_silk', name: 'Pure Kanjivaram Silk / Saree Fabric', price: 800, color: '#9B1B30', texture: 'silk' },
      { id: 'raw_silk', name: 'Luxury Raw Silk', price: 600, color: '#4A0E17', texture: 'silk' },
      { id: 'royal_velvet', name: 'Royal Velvet', price: 750, color: '#2C1B4D', texture: 'velvet' },
      { id: 'brocade', name: 'Zari Weave Brocade', price: 700, color: '#D4AF37', texture: 'brocade' },
      { id: 'organza', name: 'Sheer Organza', price: 500, color: '#E8C5C8', texture: 'organza' },
      { id: 'cotton', name: 'Handloom Soft Cotton', price: 350, color: '#0F4C81', texture: 'cotton' }
    ],
    embroidery: [
      { id: 'none', name: 'Standard Tailoring (No Embroidery)', price: 0 },
      { id: 'neckline_aari', name: 'Neckline Delicate Aari Work', price: 800 },
      { id: 'heavy_bridal_aari', name: 'Heavy Bridal Maggam / Zardozi Work', price: 2500 },
      { id: 'sleeve_border_aari', name: 'Elbow Sleeve Motif & Border Aari', price: 1200 },
      { id: 'peacock_motif', name: 'Grand Peacock / Temple Motif (Back & Sleeves)', price: 3000 }
    ],
    addOns: [
      { id: 'padding', name: 'Premium Cup Padding', price: 200 },
      { id: 'double_lining', name: 'Cotton Double Lining', price: 150 },
      { id: 'designer_latkan', name: 'Handmade Velvet & Zari Latkans/Tassels', price: 300 },
      { id: 'piping', name: 'Contrast Satin Piping', price: 100 },
      { id: 'side_zipper', name: 'Concealed Side Zipper Closure', price: 120 },
      { id: 'can_can', name: 'Can-Can Stiff Net Layer (For Frocks)', price: 350 }
    ],
    baseStitchingPrice: 650
  },
  designs: [
    {
        "id": "blouse_design_1",
        "title": "Bridal Heavy Zardozi Aari Work Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_01.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_2",
        "title": "Royal Peacock Motif Maggam Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_02.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_3",
        "title": "Traditional Kanjivaram Golden Brocade Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_03.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_4",
        "title": "Deep Neck Floral Embroidery Silk Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_04.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_5",
        "title": "South Indian Temple Border Puff Sleeve Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_05.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_6",
        "title": "Velvet Cutwork Neckline Bridal Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_06.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_7",
        "title": "Handcrafted Beadwork & Zari Accent Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_07.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_8",
        "title": "Designer Elbow Sleeve Aari Embroidery Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_08.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_9",
        "title": "Classic Round Neck Raw Silk Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_09.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_10",
        "title": "Grand Marriage Collection Kundan Work Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_10.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_11",
        "title": "Sweetheart Neck Sheer Back Aari Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_11.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_12",
        "title": "Sheer Sleeve Delicate Motif Designer Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_12.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_13",
        "title": "Heavy Latkan Accent Backless Silk Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_13.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_14",
        "title": "Contrast Border Heritage Bridal Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_14.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_15",
        "title": "Modern Mirror Work Custom Tailored Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_15.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_16",
        "title": "Bridal Heavy Zardozi Aari Work Blouse (Design #16)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_16.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_17",
        "title": "Royal Peacock Motif Maggam Blouse (Design #17)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_17.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_18",
        "title": "Traditional Kanjivaram Golden Brocade Blouse (Design #18)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_18.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_19",
        "title": "Deep Neck Floral Embroidery Silk Blouse (Design #19)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_19.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_20",
        "title": "South Indian Temple Border Puff Sleeve Blouse (Design #20)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_20.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_21",
        "title": "Velvet Cutwork Neckline Bridal Blouse (Design #21)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_21.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_22",
        "title": "Handcrafted Beadwork & Zari Accent Blouse (Design #22)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_22.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_23",
        "title": "Designer Elbow Sleeve Aari Embroidery Blouse (Design #23)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_23.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_24",
        "title": "Classic Round Neck Raw Silk Blouse (Design #24)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_24.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_25",
        "title": "Grand Marriage Collection Kundan Work Blouse (Design #25)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_25.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_26",
        "title": "Sweetheart Neck Sheer Back Aari Blouse (Design #26)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_26.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_27",
        "title": "Sheer Sleeve Delicate Motif Designer Blouse (Design #27)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_27.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_28",
        "title": "Heavy Latkan Accent Backless Silk Blouse (Design #28)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_28.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_29",
        "title": "Contrast Border Heritage Bridal Blouse (Design #29)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_29.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_30",
        "title": "Modern Mirror Work Custom Tailored Blouse (Design #30)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_30.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_31",
        "title": "Bridal Heavy Zardozi Aari Work Blouse (Design #31)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_31.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_32",
        "title": "Royal Peacock Motif Maggam Blouse (Design #32)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_32.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_33",
        "title": "Traditional Kanjivaram Golden Brocade Blouse (Design #33)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_33.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_34",
        "title": "Deep Neck Floral Embroidery Silk Blouse (Design #34)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_34.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_35",
        "title": "South Indian Temple Border Puff Sleeve Blouse (Design #35)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_35.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_36",
        "title": "Velvet Cutwork Neckline Bridal Blouse (Design #36)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_36.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_37",
        "title": "Handcrafted Beadwork & Zari Accent Blouse (Design #37)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_37.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_38",
        "title": "Designer Elbow Sleeve Aari Embroidery Blouse (Design #38)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_38.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_39",
        "title": "Classic Round Neck Raw Silk Blouse (Design #39)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_39.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_40",
        "title": "Grand Marriage Collection Kundan Work Blouse (Design #40)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_40.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_41",
        "title": "Sweetheart Neck Sheer Back Aari Blouse (Design #41)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_41.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_42",
        "title": "Sheer Sleeve Delicate Motif Designer Blouse (Design #42)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_42.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_43",
        "title": "Heavy Latkan Accent Backless Silk Blouse (Design #43)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_43.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_44",
        "title": "Contrast Border Heritage Bridal Blouse (Design #44)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_44.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_45",
        "title": "Modern Mirror Work Custom Tailored Blouse (Design #45)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_45.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_46",
        "title": "Bridal Heavy Zardozi Aari Work Blouse (Design #46)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_46.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_47",
        "title": "Royal Peacock Motif Maggam Blouse (Design #47)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_47.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_48",
        "title": "Traditional Kanjivaram Golden Brocade Blouse (Design #48)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_48.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_49",
        "title": "Deep Neck Floral Embroidery Silk Blouse (Design #49)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_49.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_50",
        "title": "South Indian Temple Border Puff Sleeve Blouse (Design #50)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_50.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_51",
        "title": "Velvet Cutwork Neckline Bridal Blouse (Design #51)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_51.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_52",
        "title": "Handcrafted Beadwork & Zari Accent Blouse (Design #52)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_52.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_53",
        "title": "Designer Elbow Sleeve Aari Embroidery Blouse (Design #53)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_53.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_54",
        "title": "Classic Round Neck Raw Silk Blouse (Design #54)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_54.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_55",
        "title": "Grand Marriage Collection Kundan Work Blouse (Design #55)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_55.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_56",
        "title": "Sweetheart Neck Sheer Back Aari Blouse (Design #56)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_56.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_57",
        "title": "Sheer Sleeve Delicate Motif Designer Blouse (Design #57)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_57.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_58",
        "title": "Heavy Latkan Accent Backless Silk Blouse (Design #58)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_58.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_59",
        "title": "Contrast Border Heritage Bridal Blouse (Design #59)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_59.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_60",
        "title": "Modern Mirror Work Custom Tailored Blouse (Design #60)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_60.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_61",
        "title": "Bridal Heavy Zardozi Aari Work Blouse (Design #61)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_61.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_62",
        "title": "Royal Peacock Motif Maggam Blouse (Design #62)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_62.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_63",
        "title": "Traditional Kanjivaram Golden Brocade Blouse (Design #63)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_63.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_64",
        "title": "Deep Neck Floral Embroidery Silk Blouse (Design #64)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_64.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_65",
        "title": "South Indian Temple Border Puff Sleeve Blouse (Design #65)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_65.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_66",
        "title": "Velvet Cutwork Neckline Bridal Blouse (Design #66)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_66.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_67",
        "title": "Handcrafted Beadwork & Zari Accent Blouse (Design #67)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_67.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_68",
        "title": "Designer Elbow Sleeve Aari Embroidery Blouse (Design #68)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Custom Design",
        "image": "/asset/blouses/blouse_68.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_69",
        "title": "Classic Round Neck Raw Silk Blouse (Design #69)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "high_collar",
        "backNeck": "bow_back",
        "sleeve": "three_fourth",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Bridal Aari",
        "image": "/asset/blouses/blouse_69.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_70",
        "title": "Grand Marriage Collection Kundan Work Blouse (Design #70)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "organza",
        "frontNeck": "deep_v",
        "backNeck": "potli_keyhole",
        "sleeve": "full",
        "embroidery": "neckline_aari",
        "price": 650,
        "badge": "Popular",
        "image": "/asset/blouses/blouse_70.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_71",
        "title": "Sweetheart Neck Sheer Back Aari Blouse (Design #71)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 650,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_71.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_72",
        "title": "Sheer Sleeve Delicate Motif Designer Blouse (Design #72)",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "boat",
        "backNeck": "open_back",
        "sleeve": "puff",
        "embroidery": "peacock_motif",
        "price": 650,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_72.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_73",
        "title": "Heavy Latkan Accent Backless Silk Blouse (Design #73)",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "royal_velvet",
        "frontNeck": "deep_u",
        "backNeck": "window_cutout",
        "sleeve": "short",
        "embroidery": "heavy_bridal_aari",
        "price": 650,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_73.jpeg",
        "description": ""
    },
    {
        "id": "blouse_design_74",
        "title": "Cyan & Magenta Contrast Petal Keyhole Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "soft_silk",
        "frontNeck": "potli_front",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 750,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_74.jpeg",
        "description": "Designer cyan-blue and magenta contrast blouse with teardrop petal keyhole back cutout and geometric border sleeve stitching."
    },
    {
        "id": "blouse_design_75",
        "title": "Royal Pink Heavy Zardozi Bridal Aari Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 1450,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_75.jpeg",
        "description": "Grand bridal pink blouse featuring heavy floral Aari neckline, vertical bullion gold sleeve line embroidery, and luxury Kundan stone embellishments."
    },
    {
        "id": "blouse_design_76",
        "title": "Silver Grey Brocade Silk Blouse with Blue Stone Aari",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "deep_u",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "peacock_motif",
        "price": 850,
        "badge": "Exclusive",
        "image": "/asset/blouses/blouse_76.jpeg",
        "description": "Rich silver-grey floral brocade blouse adorned with sapphire blue stone motifs and fine golden wire Aari border handwork."
    },
    {
        "id": "blouse_design_77",
        "title": "Deep Wine Silk Blouse with Delicate Golden Border Aari",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "deep_u",
        "backNeck": "deep_u_back",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 950,
        "badge": "Best Seller",
        "image": "/asset/blouses/blouse_77.jpeg",
        "description": "Classic deep wine-purple silk blouse tailored with elegant U-neck, golden vine Aari border, and customized handmade latkan doris."
    },
    {
        "id": "blouse_design_78",
        "title": "Emerald Green Silk Blouse with Delicate Golden Border",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "deep_u",
        "backNeck": "deep_u_back",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 850,
        "badge": "Bridal Collection",
        "image": "/asset/blouses/blouse_78.jpeg",
        "description": "Rich emerald green pure silk blouse designed with fine golden bead neck trim, short sleeves, and classic tied dori."
    },
    {
        "id": "blouse_design_79",
        "title": "Golden Copper Brocade Scalloped Neckline Puff Blouse",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "puff",
        "embroidery": "sleeve_border_aari",
        "price": 950,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_79.jpeg",
        "description": "Royal copper-gold brocade silk blouse featuring an artisanal scalloped sweetheart neckline and South Indian structured puff sleeves."
    },
    {
        "id": "blouse_design_80",
        "title": "Crimson Red Royal Floral Zardozi Bridal Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "deep_u",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "heavy_bridal_aari",
        "price": 1650,
        "badge": "Masterpiece",
        "image": "/asset/blouses/blouse_80.jpeg",
        "description": "Exquisite bridal crimson red silk blouse densely embroidered with floral vine zardozi, kundan stones, and hand-embroidered elbow sleeves."
    },
    {
        "id": "blouse_design_81",
        "title": "Peach Gold Raw Silk Blouse with Beaded Border",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "raw_silk",
        "frontNeck": "deep_u",
        "backNeck": "deep_u_back",
        "sleeve": "short",
        "embroidery": "neckline_aari",
        "price": 750,
        "badge": "New Arrival",
        "image": "/asset/blouses/blouse_81.jpeg",
        "description": "Soft peach-gold raw silk blouse styled with deep round neckline, delicate kundan border, and adjustable dori tassels."
    },
    {
        "id": "blouse_design_82",
        "title": "Sky Blue & Pastel Peach Dual Silk Blouse Set",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "kanjivaram_silk",
        "frontNeck": "sweetheart",
        "backNeck": "open_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 850,
        "badge": "Festive Duo",
        "image": "/asset/blouses/blouse_82.jpeg",
        "description": "Handcrafted traditional Kanjivaram silk blouses in vibrant sky-blue and pastel peach with rich golden zari borders and square neck cuts."
    },
    {
        "id": "blouse_design_83",
        "title": "Sky Blue Sheer Chevron Net Cutwork Aari Blouse",
        "category": "Bridal Aari",
        "garmentType": "saree_blouse",
        "fabric": "soft_silk",
        "frontNeck": "deep_u",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 1150,
        "badge": "Top Trend",
        "image": "/asset/blouses/blouse_83.jpeg",
        "description": "Artisanal sky blue blouse crafted with sheer illusion net chevron sleeves, delicate gold stone border, and custom back cutout."
    },
    {
        "id": "blouse_design_84",
        "title": "Royal Pink Checked Brocade Blouse with Zari Border",
        "category": "Blouses",
        "garmentType": "saree_blouse",
        "fabric": "brocade",
        "frontNeck": "sweetheart",
        "backNeck": "deep_u_back",
        "sleeve": "elbow",
        "embroidery": "sleeve_border_aari",
        "price": 850,
        "badge": "Festive Silk",
        "image": "/asset/blouses/blouse_84.jpeg",
        "description": "Rich royal pink checked brocade silk blouse with traditional square neckline and heavy gold Kanjivaram zari borders."
    },
    {
        "id": "blouse_design_85",
        "title": "Designer Floral Kurti & Salwar Set with Hand Embroidered V-Neck",
        "category": "Blouses",
        "garmentType": "salwar_kurti",
        "fabric": "soft_silk",
        "frontNeck": "deep_v",
        "backNeck": "deep_u_back",
        "sleeve": "three_fourth",
        "embroidery": "neckline_aari",
        "price": 950,
        "badge": "New Collection",
        "image": "/asset/blouses/blouse_85.jpeg",
        "description": "Handcrafted floral printed designer kurtis featuring hand-beaded V-neck plackets, tailored pants, and chevron printed sleeves."
    },
    {
        "id": "frock_design_1",
        "title": "Silk Saree Converted Anarkali Maxi Gown",
        "category": "Frocks",
        "garmentType": "saree_to_frock",
        "fabric": "kanjivaram_silk",
        "frockFlare": "umbrella_flare",
        "frontNeck": "boat",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 1200,
        "badge": "Saree Reuse",
        "image": "/asset/sareeconvertdress/saree_frock_01.jpeg",
        "description": "Repurposed silk saree converted into a high-flare Anarkali gown with intact zari border and custom bodice."
    },
    {
        "id": "frock_design_2",
        "title": "Royal Circular Flare Saree Reused Frock",
        "category": "Frocks",
        "garmentType": "saree_to_frock",
        "fabric": "kanjivaram_silk",
        "frockFlare": "umbrella_flare",
        "frontNeck": "boat",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 1200,
        "badge": "Saree Reuse",
        "image": "/asset/sareeconvertdress/saree_frock_02.jpeg",
        "description": "Repurposed silk saree converted into a high-flare Anarkali gown with intact zari border and custom bodice."
    },
    {
        "id": "frock_design_3",
        "title": "Tiered Layered Silk Saree Party Dress",
        "category": "Frocks",
        "garmentType": "saree_to_frock",
        "fabric": "kanjivaram_silk",
        "frockFlare": "umbrella_flare",
        "frontNeck": "boat",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 1200,
        "badge": "Saree Reuse",
        "image": "/asset/sareeconvertdress/saree_frock_03.jpeg",
        "description": "Repurposed silk saree converted into a high-flare Anarkali gown with intact zari border and custom bodice."
    },
    {
        "id": "frock_design_4",
        "title": "Kanjivaram Zari Border Designer Long Gown",
        "category": "Frocks",
        "garmentType": "saree_to_frock",
        "fabric": "kanjivaram_silk",
        "frockFlare": "umbrella_flare",
        "frontNeck": "boat",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 1200,
        "badge": "Saree Reuse",
        "image": "/asset/sareeconvertdress/saree_frock_04.jpeg",
        "description": "Repurposed silk saree converted into a high-flare Anarkali gown with intact zari border and custom bodice."
    },
    {
        "id": "frock_design_5",
        "title": "Traditional Saree Transformed Umbrella Frock",
        "category": "Frocks",
        "garmentType": "saree_to_frock",
        "fabric": "kanjivaram_silk",
        "frockFlare": "umbrella_flare",
        "frontNeck": "boat",
        "backNeck": "potli_keyhole",
        "sleeve": "elbow",
        "embroidery": "neckline_aari",
        "price": 1200,
        "badge": "Saree Reuse",
        "image": "/asset/sareeconvertdress/saree_frock_05.jpeg",
        "description": "Repurposed silk saree converted into a high-flare Anarkali gown with intact zari border and custom bodice."
    },
    {
        "id": "pleat_design_1",
        "title": "Instant 1-Minute Saree Pre-Pleating & Ironing",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "1-Min Wear",
        "image": "/asset/sareeprepleating/saree_pleat_01.jpeg",
        "description": "Professional pinless pre-pleating and neat box folding for effortless 1-minute bridal or party saree draping."
    },
    {
        "id": "pleat_design_2",
        "title": "Silk Saree Box Folding & Precision Pleat Setting",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Box Folded",
        "image": "/asset/sareeprepleating/saree_pleat_02.jpeg",
        "description": "Precise pallu and waist pleat fixing with steam ironing to ensure crisp, wrinkle-free drape all day."
    },
    {
        "id": "pleat_design_3",
        "title": "Bridal Kanjivaram Ready-to-Wear Draping & Pleating",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Bridal Special",
        "image": "/asset/sareeprepleating/saree_pleat_03.jpeg",
        "description": "Heavy bridal silk saree pre-pleating with secure hooks and pleat alignment for weddings and receptions."
    },
    {
        "id": "pleat_design_4",
        "title": "Pinless Saree Pre-Pleating & Travel Box Packing",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Travel Ready",
        "image": "/asset/sareeprepleating/saree_pleat_04.jpeg",
        "description": "Compact travel-safe saree box folding with pre-set pleats ready to wear anywhere in seconds."
    },
    {
        "id": "pleat_design_5",
        "title": "Teal Floral Designer Saree Pre-Pleating & Box Folding",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Crisp Fan Pleats",
        "image": "/asset/sareeprepleating/saree_pleat_05.jpeg",
        "description": "Exquisite teal floral printed silk saree with uniform fan pleat setting and ready-to-wear box fold."
    },
    {
        "id": "pleat_design_6",
        "title": "Royal Gold Zari Silk Saree Pre-Pleating & Pallu Setting",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Royal Zari Pleats",
        "image": "/asset/sareeprepleating/saree_pleat_06.jpeg",
        "description": "Grand golden zari silk saree pre-pleated with precision pleat alignment and steam press finish."
    },
    {
        "id": "pleat_design_7",
        "title": "Bridal Brocade Silk Saree Pre-Pleating & Boutique Box Packing",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Nakshatra Special",
        "image": "/asset/sareeprepleating/saree_pleat_07.jpeg",
        "description": "All-over heavy zari bridal silk saree pre-pleated with airtight boutique cover packing for weddings."
    },
    {
        "id": "pleat_design_8",
        "title": "Parrot Green & Contrast Purple Border Saree Pre-Pleating",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Contrast Border",
        "image": "/asset/sareeprepleating/saree_pleat_08.jpeg",
        "description": "Vibrant parrot green silk saree with structured temple border fan pleats for 1-minute effortless draping."
    },
    {
        "id": "pleat_design_9",
        "title": "Peacock Teal Floral Zari Saree Precision Pre-Pleating",
        "category": "Saree Pre-Pleating",
        "garmentType": "saree_pleating",
        "fabric": "kanjivaram_silk",
        "price": 350,
        "badge": "Precision Draping",
        "image": "/asset/sareeprepleating/saree_pleat_09.jpeg",
        "description": "Rich peacock teal silk saree with gold zari border, neat pleat pinless setting, and compact box packing."
    },
    {
        "id": "skirt_design_1",
        "title": "Kids Designer Silk Skirt & Top (Pattu Pavadai Set)",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "kanjivaram_silk",
        "price": 850,
        "badge": "Kids Ethnic Wear",
        "image": "/asset/skirtshirt/skirt_shirt_01.jpeg",
        "description": "Traditional green diamond zari weave full-length flared skirt paired with matching sleeve top for kids & festivals."
    },
    {
        "id": "skirt_design_2",
        "title": "Mustard Peplum Collar Top & Zari Flared Skirt Set",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "banarasi_silk",
        "price": 950,
        "badge": "Peter Pan Collar",
        "image": "/asset/skirtshirt/skirt_shirt_02.jpeg",
        "description": "Mustard yellow puff-sleeve peplum shirt top with gold piping belt and grand black & copper zari box pleat skirt."
    },
    {
        "id": "skirt_design_3",
        "title": "Magenta Sweetheart Crop Shirt & Peacock Zari Skirt",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "raw_silk",
        "price": 1150,
        "badge": "Boutique Exclusive",
        "image": "/asset/skirtshirt/skirt_shirt_03.jpeg",
        "description": "Royal magenta pink sweetheart neck crop top with pleated waist border and peacock blue zari temple border lehenga skirt."
    },
    {
        "id": "skirt_design_4",
        "title": "Mirror Work Wrap Shirt Top & Royal Zari Skirt Set",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "chanderi_silk",
        "price": 1350,
        "badge": "Mirror Work & Dupatta",
        "image": "/asset/skirtshirt/skirt_shirt_04.jpeg",
        "description": "Designer asymmetric crossover tie-up pink shirt blouse with mirror embellishments and festive black gold zari flared skirt."
    },
    {
        "id": "skirt_design_5",
        "title": "Pink Peplum Puff-Sleeve Top & Green Flared Skirt",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "banarasi_silk",
        "price": 950,
        "badge": "Tassel Hangings",
        "image": "/asset/skirtshirt/skirt_shirt_05.jpeg",
        "description": "Bright pink floral zari peplum top with puff sleeves, contrast bow belt, and parrot green temple border pleated skirt."
    },
    {
        "id": "skirt_design_6",
        "title": "Peacock Blue Zari Motif Top & Box Pleat Skirt",
        "category": "Skirt Shirt",
        "garmentType": "skirt_shirt",
        "fabric": "kanjivaram_silk",
        "price": 1050,
        "badge": "Custom Tailored Fit",
        "image": "/asset/skirtshirt/skirt_shirt_06.jpeg",
        "description": "Custom peacock blue silk skirt and top set tailored with gold mango zari motifs and structured box pleats for girls."
    },
    {
        "id": "chudithar_design_1",
        "title": "Tribal Folk Print Cotton Chudithar & Kurti (Front View)",
        "category": "Chudithar",
        "garmentType": "chudithar",
        "fabric": "pure_cotton",
        "price": 550,
        "badge": "Straight Cut",
        "image": "/asset/chudithar/chudithar_01.jpeg",
        "description": "Traditional ivory cotton linen kurti with blue tribal folk motifs, round neckline, and elbow puff sleeves."
    },
    {
        "id": "chudithar_design_2",
        "title": "Custom Circular Keyhole Cutout Back Neck Chudithar",
        "category": "Chudithar",
        "garmentType": "chudithar",
        "fabric": "pure_cotton",
        "price": 550,
        "badge": "Keyhole Back Neck",
        "image": "/asset/chudithar/chudithar_02.jpeg",
        "description": "Designer circular back keyhole cutout with neat piped finish and top button closure on ivory printed kurti."
    },
    {
        "id": "chudithar_design_3",
        "title": "Mustard Paisley Batik A-Line Flared Chudithar",
        "category": "Chudithar",
        "garmentType": "chudithar",
        "fabric": "chanderi_cotton",
        "price": 650,
        "badge": "A-Line Flare",
        "image": "/asset/chudithar/chudithar_03.jpeg",
        "description": "Elegant mustard and cocoa brown batik paisley printed A-line flared kurti with V-neckline and puff sleeve caps."
    },
    {
        "id": "chudithar_design_4",
        "title": "Crimson Floral Designer Kurti with Potli Buttons & Shoulder Pleats",
        "category": "Chudithar",
        "garmentType": "chudithar",
        "fabric": "cotton_silk",
        "price": 650,
        "badge": "Potli Buttons",
        "image": "/asset/chudithar/chudithar_04.jpeg",
        "description": "Vibrant crimson red & white floral printed kurti featuring asymmetrical potli button neck placket and stylish shoulder pleats."
    },
    {
        "id": "lehenga_design_1",
        "title": "Olive Collar Crop Shirt & Pastel Floral Georgette Lehenga",
        "category": "Lehenga",
        "garmentType": "lehenga_set",
        "fabric": "georgette",
        "price": 1450,
        "badge": "Indo-Western Fusion",
        "image": "/asset/lehenga/lehenga_01.jpeg",
        "description": "Modern Indo-Western fusion featuring olive green button-down collar crop shirt and flowy pastel floral printed georgette flare skirt."
    },
    {
        "id": "lehenga_design_2",
        "title": "Rose Pink Silk Blouse & Mint Floral Lehenga with Lotus Tassels",
        "category": "Lehenga",
        "garmentType": "lehenga_set",
        "fabric": "raw_silk",
        "price": 1650,
        "badge": "Lotus Tassels",
        "image": "/asset/lehenga/lehenga_02.jpeg",
        "description": "Handcrafted rose pink silk blouse with keyhole neckline and pastel mint floral flared lehenga adorned with designer lotus bud latkans."
    },
    {
        "id": "lehenga_design_3",
        "title": "Royal Velvet Sweetheart Blouse & Lavender Brocade Box Pleat Lehenga",
        "category": "Lehenga",
        "garmentType": "lehenga_set",
        "fabric": "banarasi_brocade",
        "price": 1850,
        "badge": "Velvet & Brocade",
        "image": "/asset/lehenga/lehenga_03.jpeg",
        "description": "Deep royal purple velvet structured sweetheart neck blouse with petal cutout paired with lavender metallic brocade flared box-pleat lehenga skirt."
    },
    {
        "id": "lehenga_design_4",
        "title": "Ivory Scallop Embroidered Crop Top & Pastel Striped Sequin Lehenga",
        "category": "Lehenga",
        "garmentType": "lehenga_set",
        "fabric": "organza_silk",
        "price": 1950,
        "badge": "Scallop Sequin Work",
        "image": "/asset/lehenga/lehenga_04.jpeg",
        "description": "Grand ivory designer lehenga set featuring scallop-cutout embroidered crop blouse and pastel multi-striped vertical sequin flared skirt."
    }
],
  orders: [
    {
      id: 'NK-84920',
      customerName: 'Priya Sundaram',
      phone: '+91 98765 43210',
      email: 'priya.s@example.com',
      address: 'Door 14, Gandhi Road, Tiruchengode',
      garmentType: 'saree_to_frock',
      designSpecs: {
        garmentType: 'saree_to_frock',
        frockFlare: 'umbrella_flare',
        frontNeck: 'sweetheart',
        backNeck: 'deep_u_back',
        sleeve: 'elbow',
        fabric: 'kanjivaram_silk',
        embroidery: 'heavy_bridal_aari',
        addOns: ['padding', 'designer_latkan', 'can_can']
      },
      measurements: {
        frockLength: '54',
        chest: '36',
        waist: '30',
        shoulder: '14',
        frontNeckDepth: '7',
        backNeckDepth: '10',
        armhole: '16',
        sleeveLength: '10.5',
        sleeveRound: '12'
      },
      pickupRequested: false,
      totalPrice: 4850,
      status: 'Aari / Embroidery Handwork',
      orderDate: '2026-09-02T10:30:00Z',
      expectedDelivery: '2026-09-08'
    },
    {
      id: 'NK-77103',
      customerName: 'Anitha Ramesh',
      phone: '+91 94123 88990',
      email: 'anitha.r@example.com',
      address: '22, South Car Street, Kamalar, Tiruchengode',
      garmentType: 'saree_blouse',
      designSpecs: {
        garmentType: 'saree_blouse',
        frontNeck: 'boat',
        backNeck: 'bow_back',
        sleeve: 'puff',
        fabric: 'raw_silk',
        embroidery: 'neckline_aari',
        addOns: ['double_lining']
      },
      measurements: null,
      pickupRequested: true,
      pickupAddress: '22, South Car Street, Kamalar, Tiruchengode',
      totalPrice: 2100,
      status: 'Fabric Received at Shop',
      orderDate: '2026-09-03T14:15:00Z',
      expectedDelivery: '2026-09-09'
    }
  ],
  pickups: [
    {
      id: 'PU-102',
      customerName: 'Anitha Ramesh',
      phone: '+91 94123 88990',
      address: '22, South Car Street, Kamalar, Tiruchengode',
      preferredDate: '2026-09-05',
      preferredTime: 'Morning (10 AM - 1 PM)',
      notes: 'Bringing 1 Silk Saree to convert into Frock + 1 sample reference dress to shop',
      status: 'Scheduled'
    }
  ]
};

class Store {
  constructor() {
    this.data = defaultData;
    this.load();
  }

  load() {
    try {
      if (fs.existsSync(DB_FILE)) {
        const raw = fs.readFileSync(DB_FILE, 'utf8');
        this.data = { ...defaultData, ...JSON.parse(raw) };
      } else if (fs.existsSync(BUNDLED_DB_FILE)) {
        const raw = fs.readFileSync(BUNDLED_DB_FILE, 'utf8');
        this.data = { ...defaultData, ...JSON.parse(raw) };
        this.save();
      } else {
        this.save();
      }
    } catch (e) {
      console.warn('Using default store data (Error loading database file):', e.message);
    }
  }

  save() {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf8');
    } catch (e) {
      console.warn('Store persistence notice (in-memory fallback active):', e.message);
    }
  }
}

export const db = new Store();
